# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 594)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(20, 60, 321, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(600, 60, 257, 43))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Loadpicture = QtWidgets.QPushButton(self.groupBox)
        self.Loadpicture.setGeometry(QtCore.QRect(40, 450, 181, 23))
        self.Loadpicture.setObjectName("Loadpicture")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(40, 490, 181, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 530, 181, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.savemask = QtWidgets.QPushButton(self.groupBox)
        self.savemask.setGeometry(QtCore.QRect(70, 30, 41, 16))
        self.savemask.setObjectName("savemask")
        self.exit = QtWidgets.QPushButton(self.groupBox)
        self.exit.setGeometry(QtCore.QRect(120, 30, 41, 16))
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Image"))
        self.Loadpicture.setText(_translate("Form", "Finish Object"))
        self.pushButton.setText(_translate("Form", "reset clicks"))
        self.pushButton_3.setText(_translate("Form", "undo clicks"))
        self.pushButton_4.setText(_translate("Form", "Loadpicture"))
        self.savemask.setText(_translate("Form", "savemask"))
        self.exit.setText(_translate("Form", "exit"))
